apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api
  team: devops

commonAnnotations:
  note: "Este es el ambiente de PROD"

resources:
- ns.yaml
- ../../base

patchesStrategicMerge:
  - deploy-strategic-patch.yaml

patches:
- target:
    kind: ConfigMap
    name: cm-private-api
  path: cm-patch.yaml

- target:
    kind: Ingress
    name: public-api
  path: ing-patch.yaml

- target:
    kind: Service
    name: public-api
  patch: |-
    - op: add
      path: /spec/type
      value: ClusterIP

images:
  - name: KUSTOMIZE-DEFINED
    newName: trago18/kubelabs_publicapi
    newTag: 1.0.0