apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

commonLabels:
  app: public-api
  team: devops

commonAnnotations:
  note: Este es el ambiente de STAGE

resources:
- ns.yaml
- ../../base

patchesStrategicMerge:
- deploy-strategic-patch.yaml



patches:
- path: cm-patch.yaml
  target:
    kind: ConfigMap
    name: cm-private-api
- path: ing-patch.yaml
  target:
    kind: Ingress
    name: public-api
- patch: |-
    - op: add
      path: /spec/type
      value: ClusterIP
  target:
    kind: Service
    name: public-api

images:
- name: KUSTOMIZE-DEFINED
  newName: trago18/kubelabs_publicapi
  newTag: 3.0.0
