apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-api
spec:
  destination:
    name: ''
    namespace: public
    server: 'https://kubernetes.default.svc'
  source:
    path: public-api/overlays/production
    repoURL: 'git@github.com:Trago18/ops.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true